/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;

/**
 *
 * @author valentin
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    private BadConsequence pendingBadModel;
    public void setPendingBadConsequenceView (BadConsequence b)
    {
        pendingBadModel = b;
        
        if (b != null)
        {
            if (b.isEmpty())
                badConsequenceLabel.setText(" ");
            else
                badConsequenceLabel.setText(pendingBadModel.toString());
        }
        else
            badConsequenceLabel.setText(" ");
        
        repaint();
    }
    
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        badConsequenceLabel = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(119, 1, 1));

        badConsequenceLabel.setEditable(false);
        badConsequenceLabel.setBackground(new java.awt.Color(95, 13, 1));
        badConsequenceLabel.setColumns(20);
        badConsequenceLabel.setForeground(new java.awt.Color(254, 254, 254));
        badConsequenceLabel.setLineWrap(true);
        badConsequenceLabel.setRows(5);
        badConsequenceLabel.setText("Texto del bad consequence");
        jScrollPane1.setViewportView(badConsequenceLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea badConsequenceLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
