/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;
import NapakalakiGame.TreasureKind;

/**
 *
 * @author valentin
 */
public class TreasureView extends javax.swing.JPanel {

    private Treasure treasureModel;
    private boolean selected = false;
    
    void setTreasure(Treasure t) {
        treasureModel = t;
        bonusLabel.setText(String.valueOf(t.getBonus()));
        nombreTesoroLabel.setText(treasureModel.getName());
        
        switch (treasureModel.getType())
        {
            case ONEHAND:
                tipoTesoroLabel.setText("Una mano");
                break;
            case BOTHHANDS:
                tipoTesoroLabel.setText("Dos manos");
                break;
            case SHOES:
                tipoTesoroLabel.setText("Zapatos");
                break;
            case HELMET:
                tipoTesoroLabel.setText("Casco");
                break;
            case ARMOR:
                tipoTesoroLabel.setText("Armadura");
                break;
        }
        repaint();        
    }
    
    /*
    Returns if the treasure is selected by the user
    */
    public boolean isSelected ()
    {
        return selected;
    }
    
    /*
    Returns this treasure
    */
    public Treasure getTreasure()
    {
        return treasureModel;
    }
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        nombreTesoroLabel = new javax.swing.JLabel();
        bonusLabel = new javax.swing.JLabel();
        tipoTesoroLabel = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        backgroundPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nombreTesoroLabel.setText("Nombretesoro");
        nombreTesoroLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bonusLabel.setBackground(new java.awt.Color(132, 132, 132));
        bonusLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bonusLabel.setForeground(new java.awt.Color(46, 46, 46));
        bonusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonusLabel.setText("BONUS");
        bonusLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tipoTesoroLabel.setText("Tipo de tesoro");
        tipoTesoroLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bonusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tipoTesoroLabel))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(nombreTesoroLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(nombreTesoroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bonusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoTesoroLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (selected)
        {
            selected = false;
            setBackground(new java.awt.Color(204,204,204));
            backgroundPanel.setBackground(new java.awt.Color(204,204,204));
            repaint();
        }
        else
        {
            selected = true;
            setBackground(new java.awt.Color(153,204,255));
            backgroundPanel.setBackground(new java.awt.Color(153,204,255));
            repaint();
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel bonusLabel;
    private javax.swing.JLabel nombreTesoroLabel;
    private javax.swing.JLabel tipoTesoroLabel;
    // End of variables declaration//GEN-END:variables
}
